import { Destination, Package, PackageCategory, Testimonial, GalleryImage, Review, ItineraryItem } from './types';

export const destinations: Destination[] = [
  { id: 1, name: 'Paris, France', description: 'The city of love, lights, and art.', image: 'https://picsum.photos/seed/paris/800/600.webp' },
  { id: 2, name: 'Kyoto, Japan', description: 'Experience ancient temples and serene gardens.', image: 'https://picsum.photos/seed/kyoto/800/600.webp' },
  { id: 3, name: 'Santorini, Greece', description: 'Stunning sunsets and iconic white-washed villages.', image: 'https://picsum.photos/seed/santorini/800/600.webp' },
  { id: 4, name: 'Kerala, India', description: 'Lush backwaters, serene beaches, and vibrant culture.', image: 'https://picsum.photos/seed/kerala/800/600.webp' },
  { id: 5, name: 'Machu Picchu, Peru', description: 'Explore the ancient Incan citadel high in the Andes.', image: 'https://picsum.photos/seed/machupicchu/800/600.webp' },
  { id: 6, name: 'Rome, Italy', description: 'A historic city of gladiators, art, and delicious food.', image: 'https://picsum.photos/seed/rome/800/600.webp' },
  { id: 7, name: 'Rajasthan, India', description: 'A land of majestic forts, vibrant markets, and royal history.', image: 'https://picsum.photos/seed/rajasthan/800/600.webp' },
  { id: 8, name: 'Goa, India', description: 'Sun-kissed beaches, lively nightlife, and Portuguese heritage.', image: 'https://picsum.photos/seed/goa/800/600.webp' },
  { id: 9, name: 'Bora Bora', description: 'Overwater bungalows in a tropical paradise.', image: 'https://picsum.photos/seed/borabora/800/600.webp' },
  { id: 10, name: 'Ladakh, India', description: 'High-altitude desert with stunning monasteries and landscapes.', image: 'https://picsum.photos/seed/ladakh/800/600.webp' },
  { id: 11, name: 'Varanasi, India', description: 'The spiritual capital of India on the sacred banks of the Ganges.', image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80' },
  { id: 12, name: 'Kashmir, India', description: 'Majestic snow peaks, tranquil Dal Lake shikaras, and scenic alpine valleys in Gulmarg.', image: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=800&q=80' },
  { id: 13, name: 'Agra & Delhi, India', description: 'Iconic Taj Mahal at sunrise, Mughal architecture, and historic capital monuments.', image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80' },
  { id: 14, name: 'Himachal Pradesh, India', description: 'Snowy Himalayan summits, pine forests, hot springs, and adventure sports in Solang Valley.', image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80' },
  { id: 15, name: 'Andaman Islands, India', description: 'Azure waters, white-sand Radhanagar Beach, vibrant coral reefs, and bioluminescent bays.', image: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80' },
  { id: 16, name: 'Meghalaya, India', description: 'Living root bridges, crystal-clear Dawki river, and roaring waterfalls in the Abode of Clouds.', image: 'https://images.unsplash.com/photo-1625834317417-44798b151e36?auto=format&fit=crop&w=800&q=80' },
];

export const packages: Package[] = [
  { id: 1, name: 'Romantic Paris Escape', destination: 'Paris, France', duration: '5 Days, 4 Nights', price: 99999, highlights: ['Eiffel Tower Tour', 'Louvre Museum Visit', 'Seine River Cruise'], image: 'https://picsum.photos/seed/parispack/800/600.webp', category: PackageCategory.HONEYMOON, description: 'Indulge in the romance of Paris with our specially curated escape. This package includes luxurious accommodations, private tours of iconic landmarks, and intimate dining experiences, making it the perfect getaway for couples.', itinerary: [ { day: 1, title: 'Arrival in Paris', description: 'Check into your boutique hotel and enjoy a welcome dinner cruise on the Seine.' }, { day: 2, title: 'Art & History', description: 'Morning visit to the Louvre Museum, followed by an exploration of Montmartre.' }, { day: 3, title: 'Iconic Landmarks', description: 'Ascend the Eiffel Tower and visit the Notre-Dame Cathedral.' }, { day: 4, title: 'Versailles Palace', description: 'A full-day trip to the magnificent Palace of Versailles and its gardens.' }, { day: 5, title: 'Departure', description: 'Enjoy a final Parisian breakfast before heading to the airport.' } ] },
  { id: 2, name: 'Japanese Cultural Journey', destination: 'Kyoto, Japan', duration: '7 Days, 6 Nights', price: 199999, highlights: ['Kinkaku-ji Temple', 'Arashiyama Bamboo Grove', 'Gion District Geisha Spotting'], image: 'https://picsum.photos/seed/kyotopack/800/600.webp', category: PackageCategory.CULTURAL, description: 'Immerse yourself in the ancient traditions and serene beauty of Kyoto. This journey takes you through historic temples, peaceful gardens, and the enchanting geisha district of Gion.', itinerary: [ { day: 1, title: 'Arrival in Kyoto', description: 'Arrive in Kyoto and check into a traditional Ryokan for an authentic experience.' }, { day: 2, title: 'Golden Pavilion & Zen Gardens', description: 'Visit Kinkaku-ji (Golden Pavilion) and the rock garden of Ryōan-ji.' }, { day: 3, title: 'Arashiyama', description: 'Explore the Arashiyama Bamboo Grove and Tenryū-ji Temple.' }, { day: 4, title: 'Fushimi Inari & Gion', description: 'Hike through the thousands of torii gates at Fushimi Inari Shrine and walk through the historic Gion district.' }, { day: 5, title: 'Tea Ceremony', description: 'Participate in a traditional Japanese tea ceremony and explore Nishiki Market.' }, { day: 6, title: 'Day trip to Nara', description: 'Visit Nara Park to see friendly deer and the Great Buddha at Todai-ji Temple.' }, { day: 7, title: 'Departure', description: 'Enjoy a final Japanese breakfast before your departure.' } ] },
  { id: 3, name: 'Kerala Backwater Bliss', destination: 'Kerala, India', duration: '6 Days, 5 Nights', price: 49999, highlights: ['Houseboat Stay in Alleppey', 'Munnar Tea Gardens', 'Kathakali Performance'], image: 'https://picsum.photos/seed/keralapack/800/600.webp', category: PackageCategory.FAMILY, description: 'Experience the tranquil beauty of "God\'s Own Country" with a relaxing journey through Kerala\'s backwaters, tea plantations, and vibrant cultural scenes. A perfect family retreat.', itinerary: [ { day: 1, title: 'Arrival in Cochin', description: 'Explore the historic Fort Kochi area and see the Chinese Fishing Nets.' }, { day: 2, title: 'Munnar Tea Gardens', description: 'Drive to Munnar, check into your resort, and visit a tea plantation.' }, { day: 3, title: 'Alleppey Houseboat', description: 'Travel to Alleppey and board a private houseboat for an overnight cruise through the backwaters.' }, { day: 4, title: 'Explore Thekkady', description: 'Visit the Periyar Wildlife Sanctuary and enjoy a spice plantation tour.' }, { day: 5, title: 'Cultural Evening', description: 'Return to Cochin and witness a traditional Kathakali dance performance.' }, { day: 6, title: 'Departure', description: 'Depart from Cochin with beautiful memories.' } ] },
  { id: 4, name: 'Family Fun in Rome', destination: 'Rome, Italy', duration: '6 Days, 5 Nights', price: 149999, highlights: ['Colosseum & Roman Forum', 'Vatican City Tour', 'Pizza Making Class'], image: 'https://picsum.photos/seed/romepack/800/600.webp', category: PackageCategory.FAMILY, description: 'Explore the wonders of the Eternal City with a package designed for the whole family. From ancient gladiators to delicious gelato, this trip is packed with fun and educational experiences.', itinerary: [ { day: 1, title: 'Welcome to Rome', description: 'Arrive in Rome and take a walking tour to the Trevi Fountain and Spanish Steps.' }, { day: 2, title: 'Ancient Rome', description: 'Tour the Colosseum, Roman Forum, and Palatine Hill.' }, { day: 3, title: 'Vatican City', description: 'Visit St. Peter\'s Basilica, the Vatican Museums, and the Sistine Chapel.' }, { day: 4, title: 'Pizza & Gelato', description: 'Enjoy a fun-filled pizza-making class and a gelato tasting tour.' }, { day: 5, title: 'Borghese Gardens', description: 'Relax and explore the beautiful Borghese Gardens and Gallery.' }, { day: 6, title: 'Departure', description: 'Enjoy a final Italian breakfast before departing.' } ] },
  { id: 5, name: 'Royal Rajasthan Tour', destination: 'Rajasthan, India', duration: '8 Days, 7 Nights', price: 59999, highlights: ['Jaipur City Palace', 'Udaipur Lake Pichola', 'Jodhpur Mehrangarh Fort'], image: 'https://picsum.photos/seed/rajasthanpack/800/600.webp', category: PackageCategory.CULTURAL, description: 'Step into the land of kings with a tour of Rajasthan\'s most majestic cities. Witness the grandeur of forts and palaces, and immerse yourself in the vibrant culture of India\'s desert state.', itinerary: [ { day: 1, title: 'Arrival in Jaipur', description: 'Welcome to the Pink City. Check in and visit Hawa Mahal.' }, { day: 2, title: 'Jaipur Exploration', description: 'Visit the Amber Fort, City Palace, and Jantar Mantar.' }, { day: 3, title: 'Journey to Jodhpur', description: 'Drive to the Blue City, Jodhpur. Evening at leisure.' }, { day: 4, title: 'Mehrangarh Fort', description: 'Explore the mighty Mehrangarh Fort and Jaswant Thada.' }, { day: 5, title: 'Udaipur - City of Lakes', description: 'Travel to Udaipur and enjoy an evening boat ride on Lake Pichola.' }, { day: 6, title: 'Udaipur City Tour', description: 'Visit the City Palace, Jagdish Temple, and Saheliyon-ki-Bari.' }, { day: 7, title: 'Shopping & Leisure', description: 'Explore the local markets of Udaipur for handicrafts and souvenirs.' }, { day: 8, title: 'Departure', description: 'Depart from Udaipur airport.' } ] },
  { id: 6, name: 'Goan Beach Paradise', destination: 'Goa, India', duration: '4 Days, 3 Nights', price: 29999, highlights: ['North Goa Beach Hopping', 'Old Goa Churches', 'Dudhsagar Falls Trip'], image: 'https://picsum.photos/seed/goapack/800/600.webp', category: PackageCategory.ADVENTURE, description: 'Relax and rejuvenate on the sun-kissed beaches of Goa. This short getaway is perfect for those looking to unwind by the sea, enjoy vibrant nightlife, and explore Portuguese heritage.', itinerary: [ { day: 1, title: 'Arrival in Goa', description: 'Check into your beach resort in North Goa and relax.' }, { day: 2, title: 'North Goa Fun', description: 'Explore famous beaches like Calangute, Baga, and Anjuna. Enjoy water sports.' }, { day: 3, title: 'South Goa & History', description: 'Visit Old Goa to see historic churches, followed by a trip to the serene beaches of South Goa.' }, { day: 4, title: 'Departure', description: 'Enjoy the morning at leisure before your flight home.' } ] },
  { id: 7, name: 'Peruvian Peaks Expedition', destination: 'Machu Picchu, Peru', duration: '10 Days, 9 Nights', price: 259999, highlights: ['Inca Trail Hike', 'Machu Picchu Sunrise', 'Cusco City Tour'], image: 'https://picsum.photos/seed/perupack/800/600.webp', category: PackageCategory.ADVENTURE, description: 'Embark on the adventure of a lifetime trekking the ancient Inca Trail to the lost city of Machu Picchu. This expedition is for the true adventurer seeking breathtaking landscapes and rich history.', itinerary: [ { day: 1, title: 'Arrival in Cusco', description: 'Acclimatize to the altitude in the historic city of Cusco.' }, { day: 2, title: 'Sacred Valley Tour', description: 'Explore the Sacred Valley of the Incas, visiting Pisac and Ollantaytambo.' }, { day: 3-6, title: 'Inca Trail Trek', description: 'A 4-day trek on the classic Inca Trail, camping under the stars.' }, { day: 7, title: 'Machu Picchu', description: 'Arrive at Machu Picchu through the Sun Gate at sunrise for a guided tour.' }, { day: 8, title: 'Relax in Cusco', description: 'Return to Cusco for a well-deserved rest.' }, { day: 9, title: 'Cusco City Exploration', description: 'Explore the highlights of Cusco, including Sacsayhuaman.' }, { day: 10, title: 'Departure', description: 'Depart from Cusco.' } ] },
  { id: 8, name: 'Bora Bora Bliss', destination: 'Bora Bora', duration: '7 Days, 6 Nights', price: 369999, highlights: ['Overwater Bungalow Stay', 'Snorkeling with Sharks & Rays', '4x4 Island Tour'], image: 'https://picsum.photos/seed/boraborapack/800/600.webp', category: PackageCategory.HONEYMOON, description: 'Escape to a tropical paradise with a luxurious stay in an overwater bungalow in Bora Bora. Enjoy crystal-clear turquoise waters, vibrant marine life, and ultimate relaxation.', itinerary: [ { day: 1, title: 'Arrival in Paradise', description: 'Arrive in Bora Bora and transfer to your stunning overwater bungalow.' }, { day: 2, title: 'Lagoon Exploration', description: 'Enjoy a full-day lagoon tour, including snorkeling with sharks and rays.' }, { day: 3, title: 'Island Adventure', description: 'Discover the island\'s interior on a thrilling 4x4 safari tour.' }, { day: 4, title: 'Leisure Day', description: 'Relax at your resort, enjoy the spa, or go kayaking.' }, { day: 5, 'title': 'Sunset Cruise', description: 'Experience a romantic sunset cruise with champagne.' }, { day: 6, title: 'Watersports', description: 'Try paddleboarding or jet skiing in the calm lagoon.' }, { day: 7, title: 'Departure', description: 'Enjoy a final morning in paradise before your departure.' } ] },
  { id: 9, name: 'Himalayan Adventure in Ladakh', destination: 'Ladakh, India', duration: '7 Days, 6 Nights', price: 79999, highlights: ['Pangong Lake Visit', 'Nubra Valley Camel Safari', 'Leh Monasteries Tour'], image: 'https://picsum.photos/seed/ladakhpack/800/600.webp', category: PackageCategory.ADVENTURE, description: 'Journey to the "Land of High Passes" for a spectacular adventure in Ladakh. Witness dramatic landscapes, serene monasteries, and the unique culture of this Himalayan desert.', itinerary: [ { day: 1, title: 'Arrival in Leh', description: 'Fly into Leh and acclimatize to the high altitude (11,500 ft).' }, { day: 2, title: 'Leh Monasteries', description: 'Visit prominent monasteries around Leh like Thiksey and Hemis.' }, { day: 3, title: 'Nubra Valley', description: 'Drive over the Khardung La pass to Nubra Valley. Enjoy a camel safari on sand dunes.' }, { day: 4, title: 'Pangong Lake', description: 'Travel to the breathtaking Pangong Tso, a high-altitude salt-water lake.' }, { day: 5, title: 'Return to Leh', description: 'Drive back to Leh from Pangong, enjoying the scenic route.' }, { day: 6, title: 'Shanti Stupa', description: 'Visit Shanti Stupa for panoramic views of Leh and enjoy some souvenir shopping.' }, { day: 7, title: 'Departure', description: 'Depart from Leh with amazing memories of the Himalayas.' } ] },
  { id: 10, name: 'Greek Islands Adventure', destination: 'Santorini, Greece', duration: '8 Days, 7 Nights', price: 179999, highlights: ['Oia Sunset Viewing', 'Volcano Tour', 'Red Beach Exploration'], image: 'https://picsum.photos/seed/santorinipack/800/600.webp', category: PackageCategory.ADVENTURE, description: 'Discover the magic of the Greek Islands on this trip to iconic Santorini. Famous for its stunning sunsets, white-washed villages, and volcanic beaches, it\'s a photographer\'s paradise.', itinerary: [ { day: 1, title: 'Welcome to Santorini', description: 'Arrive and check into your hotel overlooking the caldera.' }, { day: 2, title: 'Fira & Imerovigli', description: 'Explore the capital Fira and walk the scenic trail to Imerovigli.' }, { day: 3, title: 'Volcano & Hot Springs', description: 'Take a boat tour to the active volcano, swim in the hot springs, and visit Thirassia.' }, { day: 4, title: 'Oia Sunset', description: 'Spend the day in the picturesque village of Oia and witness its world-famous sunset.' }, { day: 5, title: 'Beach Day', description: 'Discover Santorini\'s unique beaches, including the Red Beach and black sand beaches of Perissa.' }, { day: 6, title: 'Wine Tasting', description: 'Visit local wineries to taste the unique volcanic wines of Santorini.' }, { day: 7, title: 'Ancient Akrotiri', description: 'Explore the archaeological site of Akrotiri, a prehistoric Minoan city.' }, { day: 8, title: 'Departure', description: 'Enjoy a last Greek coffee before your departure.' } ] },
  { id: 11, name: 'Varanasi Spiritual & Cultural Journey', destination: 'Varanasi, India', duration: '4 Days, 3 Nights', price: 34999, highlights: ['Sunrise Boat Ride on Ganges', 'Evening Ganga Aarti Ceremony', 'Sarnath Buddhist Tour', 'Kashi Vishwanath Temple Walk'], image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80', category: PackageCategory.CULTURAL, description: 'Immerse your soul in the timeless spiritual heart of India. Witness the mystical Ganga Aarti, explore ancient ghats and sacred temples, and walk in the footsteps of Buddha at Sarnath with private guided tours.', itinerary: [ { day: 1, title: 'Arrival & Evening Ganga Aarti', description: 'Arrive in Varanasi, check into your heritage hotel, and experience the mesmerizing evening Ganga Aarti at Dashashwamedh Ghat from a private boat.' }, { day: 2, title: 'Sunrise Boat Ride & Ghats Walking Tour', description: 'Dawn boat ride along the Ghats witnessing morning prayers and rituals, followed by a heritage walk through the ancient alleyways and Kashi Vishwanath corridor.' }, { day: 3, title: 'Sarnath Excursion & Silk Weaving', description: 'Visit Sarnath where Lord Buddha delivered his first sermon, see the Dhamek Stupa and museum, followed by a visit to traditional Banarasi silk weavers.' }, { day: 4, title: 'Morning Blessings & Departure', description: 'Enjoy sunrise over the river with traditional Banarasi breakfast (Kachori Jalebi) before transfer to the airport.' } ] },
  { id: 12, name: 'Kashmir Paradise: Dal Lake & Gulmarg', destination: 'Kashmir, India', duration: '6 Days, 5 Nights', price: 44999, highlights: ['Luxury Dal Lake Houseboat Stay', 'Gulmarg Gondola to Apharwat Peak', 'Pahalgam Betaab Valley Excursion', 'Mughal Gardens of Srinagar'], image: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=800&q=80', category: PackageCategory.HONEYMOON, description: 'Experience paradise on earth with snow-capped Pir Panjal peaks, peaceful stays on vintage wooden houseboats on Dal Lake, and thrilling cable car rides in Gulmarg.', itinerary: [ { day: 1, title: 'Arrival & Sunset Shikara Cruise', description: 'Arrive at Srinagar airport, transfer to an ornate cedar houseboat on Dal Lake, and enjoy an evening Shikara boat ride with kahwa tea.' }, { day: 2, title: 'Mughal Gardens & Shankaracharya Temple', description: 'Visit Shalimar Bagh, Nishat Bagh, and the historic Shankaracharya Hilltop Temple overlooking the valley.' }, { day: 3, title: 'Gulmarg Snow Valley & Gondola Ride', description: 'Drive through pine forests to Gulmarg. Take the world-famous Phase 2 Gondola up to Apharwat Peak (13,780 ft).' }, { day: 4, title: 'Pahalgam Valley of Shepherds', description: 'Travel along the Lidder River to scenic Pahalgam. Visit Betaab Valley and Chandanwari meadows.' }, { day: 5, title: 'Aru Valley & Baisaran Mini Switzerland', description: 'Enjoy horseback trekking into Baisaran meadows surrounded by dense fir woods and mountain peaks.' }, { day: 6, title: 'Saffron Fields of Pampore & Departure', description: 'Visit historic saffron fields and dry fruit orchards before transferring to Srinagar Airport.' } ] },
  { id: 13, name: 'Golden Triangle: Taj Mahal & Mughal Splendors', destination: 'Agra & Delhi, India', duration: '5 Days, 4 Nights', price: 38999, highlights: ['Sunrise at the Taj Mahal', 'Agra Fort & Mehtab Bagh Sunset', 'Old Delhi Rickshaw Food Tour & Jama Masjid', 'Qutub Minar & Humayun\'s Tomb'], image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80', category: PackageCategory.CULTURAL, description: 'Discover the world\'s greatest monument of love and the storied history of Mughal emperors across Delhi, Agra, and Fatehpur Sikri.', itinerary: [ { day: 1, title: 'Old Delhi Heritage & Spice Market', description: 'Arrive in the capital. Explore the Red Fort, Jama Masjid, and a thrilling rickshaw ride through Chandni Chowk.' }, { day: 2, title: 'Lutyens\' Delhi & UNESCO Landmarks', description: 'Visit Qutub Minar, Humayun\'s Tomb, India Gate, and the President\'s Estate before driving towards Agra.' }, { day: 3, title: 'Agra Fort & Mehtab Bagh Sunset', description: 'Check into your Agra hotel, tour the red sandstone Agra Fort, and watch the Taj Mahal glow at sunset across the Yamuna.' }, { day: 4, title: 'Sunrise Wonder at Taj Mahal', description: 'Experience the Taj Mahal at dawn as the marble reflects pastel sunbeams, followed by artisan marble inlay workshops.' }, { day: 5, title: 'Fatehpur Sikri & Departure', description: 'Explore Akbar\'s preserved imperial ghost city at Fatehpur Sikri before returning to Delhi airport.' } ] },
  { id: 14, name: 'Himachal Mountain Haven: Manali & Rohtang', destination: 'Himachal Pradesh, India', duration: '6 Days, 5 Nights', price: 36999, highlights: ['Rohtang Pass & Atal Tunnel', 'Solang Valley Paragliding & Zipline', 'Old Manali Cafes & Hadimba Temple', 'Beas River Rafting & Hot Springs'], image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80', category: PackageCategory.ADVENTURE, description: 'Breathe crisp Himalayan air in the scenic Kullu-Manali valley. Perfect for adventure lovers and nature enthusiasts seeking snowy slopes and pine forests.', itinerary: [ { day: 1, title: 'Arrival in Manali & Hadimba Temple', description: 'Check into your cedar chalet and stroll through ancient cedar groves to Hadimba Devi Temple.' }, { day: 2, title: 'Solang Valley Action & Paragliding', description: 'Excursion to Solang Valley for paragliding, zorbing, and cable car rides with panoramic mountain vistas.' }, { day: 3, title: 'Atal Tunnel & High Rohtang Snow Peak', description: 'Cross through the engineering marvel of Atal Tunnel to Lahaul Valley and Rohtang Pass snow viewpoints.' }, { day: 4, title: 'Naggar Castle & Heritage Art Gallery', description: 'Visit the 500-year-old timber and stone Naggar Castle, Nicholas Roerich art estate, and trout farms.' }, { day: 5, title: 'Beas River Rafting & Vashisht Springs', description: 'White-water rafting along the Beas River and relaxing natural sulfur mineral baths in Vashisht.' }, { day: 6, title: 'Old Manali Shopping & Departure', description: 'Pick up authentic Kullu woolen shawls, local apple jams, and board return transfer.' } ] },
  { id: 15, name: 'Andaman Tropical Escapade: Havelock & Neil', destination: 'Andaman Islands, India', duration: '6 Days, 5 Nights', price: 54999, highlights: ['Radhanagar Beach Sunset (Asia\'s Best)', 'Scuba Diving at Elephant Beach Coral Reef', 'Cellular Jail Light & Sound Show', 'Neil Island Natural Rock Bridge'], image: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80', category: PackageCategory.HONEYMOON, description: 'Immerse in turquoise waters, virgin white-sand shores, and world-class scuba diving across Port Blair, Havelock Island, and Neil Island.', itinerary: [ { day: 1, title: 'Port Blair & Cellular Jail Memorial', description: 'Arrive at Port Blair, visit the historic Cellular Jail National Memorial and attend the evening Light & Sound show.' }, { day: 2, title: 'Catamaran to Havelock & Radhanagar Sunset', description: 'Board luxury catamaran to Swaraj Dweep (Havelock Island) and watch an unforgettable golden sunset at Radhanagar Beach.' }, { day: 3, title: 'Elephant Beach Scuba & Coral Snorkeling', description: 'Boat trip to Elephant Beach for guided scuba diving among live coral reefs, clownfish, and sea turtles.' }, { day: 4, title: 'Cruise to Neil Island & Laxmanpur Beach', description: 'Ferry to Shaheed Dweep (Neil Island), explore secluded beaches, and view bioluminescent plankton at night.' }, { day: 5, title: 'Natural Rock Bridge & Return to Port Blair', description: 'Visit the famous living corals of Howrah Natural Bridge at low tide before cruising back to Port Blair.' }, { day: 6, title: 'Chatham Island & Island Departure', description: 'Visit Asia\'s oldest saw mill and local seashell craft markets before your airport departure.' } ] },
  { id: 16, name: 'Meghalaya: Living Roots & Crystal Rivers', destination: 'Meghalaya, India', duration: '5 Days, 4 Nights', price: 39999, highlights: ['Double Decker Living Root Bridge Trek', 'Crystal-Clear Umngot River Boat Ride in Dawki', 'Nohkalikai Falls & Mawsmai Caves', 'Shillong Scotland of the East Tour'], image: 'https://images.unsplash.com/photo-1625834317417-44798b151e36?auto=format&fit=crop&w=800&q=80', category: PackageCategory.ADVENTURE, description: 'Trek into the lush emerald rainforests of Meghalaya. Discover centuries-old bio-engineered root bridges, limestone caves, and transparent river currents along the Bangladesh border.', itinerary: [ { day: 1, title: 'Guwahati to Shillong via Umiam Lake', description: 'Drive past scenic pine hills to Shillong, stopping for water sports and sunset photography at serene Umiam Lake.' }, { day: 2, title: 'Cherrapunji Waterfalls & Limestone Caves', description: 'Visit India\'s tallest plunge waterfall (Nohkalikai Falls), Seven Sisters Falls, and lit passageways of Mawsmai Cave.' }, { day: 3, title: 'Double Decker Living Root Bridge Trek', description: 'Hike through Khasi tribal rainforests to the world-famous bio-engineered Double Decker Living Root Bridge in Nongriat.' }, { day: 4, title: 'Transparent Dawki River & Cleanest Village', description: 'Take a boat that appears to float on air over crystal-clear Umngot River in Dawki, then visit Mawlynnong village.' }, { day: 5, title: 'Laitlum Grand Canyons & Departure', description: 'Breathtaking panoramic edge views at Laitlum Canyons before highway drive back to Guwahati Airport.' } ] },
];

export const testimonials: Testimonial[] = [
  { id: 1, quote: 'Global Connect made our dream honeymoon a reality! Every detail was perfect, and the experience was unforgettable.', author: 'John & Jane Doe', location: 'Paris Trip' },
  { id: 2, quote: 'An amazing adventure from start to finish. The guides were knowledgeable and friendly. Highly recommend the Inca Trail package!', author: 'Samantha Bee', location: 'Peru Expedition' },
  { id: 3, quote: 'Our family had the time of our lives in Rome. The pizza-making class was a huge hit with the kids. Thank you, Global Connect!', author: 'The Smith Family', location: 'Rome Tour' },
  { id: 4, quote: 'The Kerala backwaters were so serene and beautiful. Global Connect organized a fantastic trip for us.', author: 'Aarav & Priya', location: 'Kerala Tour'}
];

export const galleryImages: GalleryImage[] = [
  { id: 1, src: 'https://picsum.photos/seed/gallery1/800/600.webp', alt: 'Happy couple on a beach' },
  { id: 2, src: 'https://picsum.photos/seed/gallery2/800/600.webp', alt: 'Mountain landscape with hikers' },
  { id: 3, src: 'https://picsum.photos/seed/gallery3/800/600.webp', alt: 'Historic city street' },
  { id: 4, src: 'https://picsum.photos/seed/gallery4/800/600.webp', alt: 'Family enjoying a tour' },
  { id: 5, src: 'https://picsum.photos/seed/gallery5/800/600.webp', alt: 'Beautiful sunset over the ocean' },
  { id: 6, src: 'https://picsum.photos/seed/gallery6/800/600.webp', alt: 'Famous landmark' },
  { id: 7, src: 'https://picsum.photos/seed/gallery7/800/600.webp', alt: 'Exotic wildlife' },
  { id: 8, src: 'https://picsum.photos/seed/gallery8/800/600.webp', alt: 'Delicious local food' },
  { id: 9, src: 'https://picsum.photos/seed/gallery9/800/600.webp', alt: 'Group photo of travelers' },
];

export const reviews: Review[] = [
    { id: 1, packageId: 1, author: 'Emily Carter', rating: 5, comment: 'The Romantic Paris Escape was absolutely magical. Global Connect handled everything flawlessly.', packageName: 'Romantic Paris Escape' },
    { id: 2, packageId: 7, author: 'Markus Chen', rating: 5, comment: 'An adventure of a lifetime! The Peruvian Peaks Expedition challenged me and rewarded me with breathtaking views.', packageName: 'Peruvian Peaks Expedition' },
    { id: 3, packageId: 4, author: 'The Williams Family', rating: 4, comment: 'Our kids loved the Family Fun in Rome package. The tour guides were fantastic with children. Only wish it was a day longer!', packageName: 'Family Fun in Rome' },
];